# Home Assistant Configuration
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 22
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml
  auth_providers: 
   - type: trusted_networks 
     trusted_networks: 
      - 127.0.0.1 
      - ::1 
      - 192.168.0.0/24
   - type: homeassistant

# Config
discovery:
  ignore:
    - sabnzbd
    - apple_tv
    - samsung_tv
  enable:
    - homekit
customizer:
  custom_ui: local

tts:
  - platform: google

frontend:
  themes: !include themes.yaml
  javascript_version: auto

http:
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

config:

stream:

updater:

mobile_app:

sun:

cloud:

group: !include groups.yaml

automation: !include automations.yaml

script: !include scripts.yaml

sensor: !include sensor.yaml

binary_sensor: !include binary_sensors.yaml

camera: !include camera.yaml

media_player: !include media_player.yaml

light: !include light.yaml

switch: !include switch.yaml

input_boolean: !include input_boolean.yaml

zone: !include zone.yaml

device_tracker: !include device_tracker.yaml

alarm_control_panel: !include alarms.yaml

scene: !include scenes.yaml

shell_command: !include shell_command.yaml

input_select: !include input_select.yaml

weather:
  - platform: darksky
    api_key: !secret darksky
    mode: daily

shopping_list:

conversation:

history:
  exclude:
    domains:
      - automation
      - script
      - updater
      - weblink
      - group

logbook:

map:

lovelace:
  mode: yaml
      
system_health:

# iOS and Notifications

ios:
  push:
    categories:
      - name: Afzuigkap Alert
        identifier: 'afzuigkap_alert'
        actions:
          - identifier: 'AFZUIGKAP_UITZETTEN'
            title: 'Afzuigkap Uitschakelen'
          - identifier: 'AFZUIGKAP_ANNULEREN'
            title: 'Annuleren'
            destructive: yes
      - name: Alarm Alert
        identifier: 'alarm_alert'
        actions:
          - identifier: 'ALARM_UITSCHAKELEN'
            title: 'Alarm Uitschakelen'
          - identifier: 'ALARM_ANNULEREN'
            title: 'Annuleren'
            destructive: yes
      - name: Smoke Alert
        identifier: 'smoke_alert'
        actions:
          - identifier: 'SMOKE_ALARM_INSCHAKELEN'
            title: 'Rookmelder Dempen (Tijdelijk)'
          - identifier: 'SMOKE_ANNULEREN'
            title: 'Annuleren'
            destructive: yes
      - name: Receiver Aanzetten
        identifier: 'receiver_alert'
        actions:
          - identifier: 'RECEIVER_INSCHAKELEN'
            title: 'Receiver Inschakelen'
          - identifier: 'TV_UITSCHAKELEN'
            title: 'TV Uitschakelen'
          - identifier: 'RECEIVER_ANNULEREN'
            title: 'Annuleren'
            destructive: yes
      - name: Alarm Activeren
        identifier: 'alarm_activeren'
        actions:
          - identifier: 'ALARM_AFWEZIG'
            title: 'Alarm Afwezig'
          - identifier: 'ALARM_THUIS'
            title: 'Alarm Thuis'
          - identifier: 'ALARM_ANNULEREN'
            title: 'Annuleren'
            destructive: yes
      - name: Droger Alert
        identifier: 'droger_alert'
        actions:
          - identifier: 'DROGER_UITSCHAKELEN'
            title: 'Droger Uitschakelen'
          - identifier: 'VAATWASSER_INSCHAKELEN'
            title: 'Vaatwasser Inschakelen'
          - identifier: 'DROGER_ANNULEREN'
            title: 'Annuleren'
            destructive: yes
      - name: Wasmachine Alert
        identifier: 'wasmachine_alert'
        actions:
          - identifier: 'WASMACHINE_UITSCHAKELEN'
            title: 'Wasmachine Uitschakelen'
          - identifier: 'VAATWASSER_INSCHAKELEN'
            title: 'Vaatwasser Inschakelen'
          - identifier: 'WASMACHINE_ANNULEREN'
            title: 'Annuleren'
            destructive: yes
      - name: Vaatwasser Alert
        identifier: 'vaatwasser_alert'
        actions:
          - identifier: 'VAATWASSER_UITSCHAKELEN'
            title: 'Vaatwasser Uitschakelen'
          - identifier: 'VAATWASSER_ANNULEREN'
            title: 'Annuleren'
            destructive: yes
      - name: Bijkeuken Alert
        identifier: 'bijkeuken_alert'
        actions:
          - identifier: 'SLA_ALARM'
            title: 'SLA ALARM'
            destructive: yes
          - identifier: 'AFWEZIG_ALARM'
            title: 'Alarm Afwezig'
            destructive: yes
          - identifier: 'THUIS_ALARM'
            title: 'Alarm Thuis'
          - identifier: 'BIJKEUKEN_ANNULEREN'
            title: 'Annuleren'
            destructive: yes
      - name: Toilet Alert
        identifier: 'toilet_alert'
        actions:
          - identifier: 'SLA_ALARM'
            title: 'SLA ALARM'
            destructive: yes
          - identifier: 'AFWEZIG_ALARM'
            title: 'Alarm Afwezig'
            destructive: yes
          - identifier: 'THUIS_ALARM'
            title: 'Alarm Thuis'
          - identifier: 'TOILET_ANNULEREN'
            title: 'Annuleren'
            destructive: yes
      - name: Meds Alert
        identifier: 'meds_alert'
        actions:
          - identifier: 'MEDS_ALARM'
            title: 'Voltooid'
          - identifier: 'MEDS_ANNULEREN'
            title: 'Herhaal over 20min'
            destructive: yes
      - name: Camera
        identifier: 'camera'
        actions:
          - identifier: 'SLA_ALARM'
            title: 'SLA ALARM'
            destructive: yes
            authenticationRequired: true
          - identifier: 'AFWEZIG_ALARM'
            title: 'Alarm Inschakelen'
          - identifier: 'TOILET_ANNULEREN'
            title: 'Annuleren'
            destructive: yes

# Homekit Configuration
homekit:
  auto_start: False
  filter:
    include_domains:
      - alarm_control_panel
      - light
      - sensor
      - switch
      - binary_sensor
      - input_boolean
      - media_player
      - climate
      - scene
    include_entities:
      - alarm_control_panel.home_alarm
      - input_boolean.badkamer_hass
    exclude_entities:
      - binary_sensor.floorplan
      - light.keuken
      - light.balkon
      - light.toilet
      - light.bijkeuken
      - light.kleine_kamer
      - light.balkonlamp
      - light.bijkeukenlamp
      - light.keukenlamp_a
      - light.keukenlamp_b
      - light.keukenlamp_c
      - light.kleine_kamer_lamp_a
      - light.kleine_kamer_lamp_b
      - light.kleine_kamer_lamp_c
      - light.toiletlamp
      - light.nachtkastje_jimmy
      - light.nachtkastje_stephanie_2
      - light.nachtkastje_stephanie
      - light.slaapkamer
      - sensor.weer_temperature_min
      - sensor.weer_temperature_max
      - sensor.weer_pressure
      - sensor.weer_visibility
      - sensor.weer_condition
      - sensor.weer_current
      - light.tradfri_group7e21455204400026131085
      - light.tradfri_group_7
      - input_boolean.badkamer_ha2
      - light.tradfri_bulb_e27_ws_opal_980lm_4
      - light.vloerlamp_2
      - light.vloerlamp
      - light.tafel_lamp
      - light.tafellampje
      - light.eettafel_lamp
      - light.woonkamer_plafond
      - sensor.woonkamer_humidity
      - sensor.woonkamer_temperature
      - sensor.kleine_kamer_temperature
      - sensor.kleine_kamer_humidity
      - light.keuken_plafondlampen
      - light.kleine_kamer_plafondlampen
      - switch.receiver
      - switch.air_fryer
      - switch.Printer
      - light.keukenspots
      - switch.waterkoker
      - switch.afzuigkap
      - input_boolean.badkamer_hass
      - input_boolean.lovelace_animals_tala_showbuttons
      - sensor.dark_sky_temperature_0
      - camera.dafang_motion_snapshot
      - cover.dafang_move_left_right
      - cover.dafang_move_up_down
      - sensor.dafang_light_sensor
      - switch.dafang_blue_led
      - switch.dafang_h264_rtsp_server
      - switch.dafang_ir_filter
      - switch.dafang_ir_led
      - switch.dafang_mjpeg_rtsp_server
      - switch.dafang_motion_detection
      - switch.dafang_motion_send_mail
      - switch.dafang_motion_send_telegram
      - switch.dafang_motion_tracking
      - switch.dafang_night_mode_auto
      - switch.dafang_yellow_led
      - light.vloerled
      - light.bedled
      - light.dressoirled
      - light.tvled
      - light.bankled
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_cloud_coverage_0
      - sensor.dark_sky_cloud_coverage_2
      - sensor.dark_sky_cloud_coverage_3
      - sensor.dark_sky_cloud_coverage_1
      - sensor.dark_sky_cloud_coverage_4
      - sensor.dark_sky_cloud_coverage_5
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_daytime_high_apparent_temperature_0
      - sensor.dark_sky_daytime_high_apparent_temperature_1
      - sensor.dark_sky_daytime_high_apparent_temperature_2
      - sensor.dark_sky_daytime_high_apparent_temperature_3
      - sensor.dark_sky_daytime_high_apparent_temperature_4
      - sensor.dark_sky_daytime_high_apparent_temperature_5
      - sensor.dark_sky_daytime_high_temperature_0
      - sensor.dark_sky_daytime_high_temperature_1
      - sensor.dark_sky_daytime_high_temperature_2
      - sensor.dark_sky_daytime_high_temperature_3
      - sensor.dark_sky_daytime_high_temperature_4
      - sensor.dark_sky_daytime_high_temperature_5
      - sensor.dark_sky_dew_point
      - sensor.dark_sky_dew_point_0
      - sensor.dark_sky_dew_point_1
      - sensor.dark_sky_dew_point_2
      - sensor.dark_sky_dew_point_3
      - sensor.dark_sky_dew_point_4
      - sensor.dark_sky_dew_point_5
      - sensor.dark_sky_humidity_0
      - sensor.dark_sky_humidity_1
      - sensor.dark_sky_humidity_2
      - sensor.dark_sky_humidity_3
      - sensor.dark_sky_humidity_4
      - sensor.dark_sky_humidity_5
      - sensor.dark_sky_overnight_low_apparent_temperature_0
      - sensor.dark_sky_overnight_low_apparent_temperature_1
      - sensor.dark_sky_overnight_low_apparent_temperature_2
      - sensor.dark_sky_overnight_low_apparent_temperature_3
      - sensor.dark_sky_overnight_low_apparent_temperature_4
      - sensor.dark_sky_overnight_low_apparent_temperature_5
      - sensor.dark_sky_overnight_low_temperature_0
      - sensor.dark_sky_overnight_low_temperature_1
      - sensor.dark_sky_overnight_low_temperature_2
      - sensor.dark_sky_overnight_low_temperature_3
      - sensor.dark_sky_overnight_low_temperature_4
      - sensor.dark_sky_overnight_low_temperature_5
  entity_config:
    media_player.slaapkamer_apple_tv_2:
      name: Slaapkamer Apple TV
      feature_list:
        - feature: play_pause
    alarm_control_panel.home_alarm:
      code: !secret alarm_code

# Sabnzbd
sabnzbd:
  api_key: !secret sabnzbd_api_key
  host: 192.168.0.34
  name: sabnzbd
  port: 8081
  sensors:
    - current_status
    - speed
    - queue_count
    - queue_size
    - queue_remaining
    - disk_size
    - disk_free
    - total_size

# Iframe
panel_iframe:
  sonarr:
    title: "Sonarr"
    url: !secret url_2
    icon: "mdi:television"
  couchpotato:
    title: "Radarr"
    url: !secret url_3
    icon: "mdi:sofa"
  serveressentials:
    title: "Windows Cloud"
    url: !secret url_1
    icon: "mdi:windows"

# Notify
notify:
  - name: ios_notifier
    platform: group
    services:
      - service: ios_iphone_jimmy
      - service: ios_iphone_van_steph

# Calendar
calendar:
  - platform: caldav
    url: !secret url_4
    username: !secret icloud_user
    password: !secret icloud_app_specific_password
    calendars:
      - 'Schings'
      - 'Jimmy'
      - 'Stephanie'
      - 'Holiday'

# Tado
tado:
  username: !secret tado_usr
  password: !secret tado_pwd

# Custom Updater
custom_updater:
  track:
    - components
    - cards
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/kuuji/button-card/master/tracker.json
    - https://raw.githubusercontent.com/nervetattoo/simple-thermostat/allow-updates/tracker.json
    - https://raw.githubusercontent.com/bramkragten/custom-ui/master/updater.json
    - https://raw.githubusercontent.com/ljmerza/calendar-card/master/custom_updater.json
    - https://raw.githubusercontent.com/kalkih/simple-weather-card/master/tracker.json
  component_urls:
    - https://raw.githubusercontent.com/eelcohn/home-assistant-rdw/master/custom_updater.json

# Person
person:
  - name: Jimmy
    id: !secret personid1
    user_id: !secret user_id1
    device_trackers:
      - device_tracker.iphone_jimmy
      - device_tracker.jimmys_iphone
      - device_tracker.40_98_ad_99_87_f3
  - name: Stephanie
    id: !secret personid2
    user_id: !secret user_id2
    device_trackers:
      - device_tracker.iphone_van_steph
      - device_tracker.stephanies_iphone
      - device_tracker.a4_d9_31_ce_cd_5b

# Utility
utility_meter:
  daily_energy:
    source: group.energy_kwh
    cycle: daily
    tariffs:
      - peak
      - offpeak
  monthly_energy:
    source: group.energy_kwh
    cycle: weekly
    tariffs:
      - peak
      - offpeak

speedtestdotnet:
  scan_interval:
    minutes: 240
  server_id: 12372
  monitored_conditions:
    - ping
    - download
    - upload

# Apple TV
apple_tv:
  - host: 192.168.0.95
    login_id: !secret atv_loginid
    name: Woonkamer Apple TV
    credentials: !secret atv_pwd
  - host: 192.168.0.96
    login_id: !secret atv_loginid
    name: Slaapkamer Apple TV

# Xiaomi Aqara/Mija
xiaomi_aqara:
  gateways:
    - key: !secret xiaomi_gateway
  discovery_retry: 10

